version: '3.8'

services:
  app:
    image: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/passportextra
    command: ["/bin/sh", "./wait-for-it.sh", "mongodb:27017", "-t", "30", "--", "npm", "run", "dev"]
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

